name: morl
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - about-time==4.2.1
      - alive-progress==3.3.0
      - annotated-types==0.7.0
      - attrs==25.4.0
      - autograd==1.8.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - clarabel==0.11.1
      - click==8.3.1
      - cloudpickle==3.1.2
      - cma==4.4.1
      - contourpy==1.3.2
      - cvxpy==1.7.5
      - cycler==0.12.1
      - decorator==5.2.1
      - deprecated==1.3.1
      - farama-notifications==0.0.4
      - filelock==3.20.0
      - fire==0.7.1
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - graphemeu==0.7.2
      - gymnasium==1.2.2
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mo-gymnasium==1.3.1
      - moocore==0.1.10
      - morl-baselines==1.2.0
      - moviepy==2.2.1
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==1.26.4
      - osqp==1.0.5
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - platformdirs==4.5.1
      - pluggy==1.6.0
      - proglog==0.1.12
      - protobuf==6.33.2
      - py==1.11.0
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygame==2.6.1
      - pymoo==0.6.1.6
      - pyparsing==3.2.5
      - pytest==7.1.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - scipy==1.15.3
      - scs==3.2.9
      - seaborn==0.13.2
      - sentry-sdk==2.47.0
      - six==1.17.0
      - smmap==5.0.2
      - sortedcontainers==2.4.0
      - sympy==1.14.0
      - termcolor==3.2.0
      - tomli==2.3.0
      - torch==2.9.1
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.6.2
      - wandb==0.23.1
      - wrapt==2.0.1
prefix: /Users/duanyunfei/miniconda3/envs/morl
